:arrow_up::one::one: migrated pos_disable_payment_restaurant, pos_receipt_custom, pos_order_receipt_custom, pos_discount_absolute (it-projects-llc/addons-dev#560)
* [FIX] error on empty multi-session field

* [FIX] rendering of pos after removing an order [FIX] parentNode of undefined

* [FIX] get_orderlines of null whilst removing an orderline

* [FIX] validation and extra lines fixes (#457)

* [FIX] TypeError: self.new_client is null when `Pay Full Debt

* [FIX] customer is reseted after clicking Pay Full Debt

* [FIX] travis error undefined is not a function

* [FIX] get_paymentlines of null

* [LINT]

* [LINT] move description to README

* [10.0][FIX] compatibility pos_order_cancel and pos_orderline_absolute_discount modules (#696)

* [FIX] compatibility pos_order_cancel with pos_orderline_absolute_discount

* [10.0][FIX] error on removing right after updating an order  request for order removing must be done after or instead of the request for updating.  Without this update, the script could send a request for an update after sending a request for removing the order. The scenario:   * update order -- timer start * remove order -- the request is sent immediately * timer ends -- request for updating is sent (#683)

* [FIX] sync error during fast change the order

* [DOC] clean up and more information(#694)

* [FIX] Issue ``parentNode is undefined`` after order bill splitting(#699)

* [FIX]: Issue ``parentNode is undefined`` after order bill splitting

* [10.0][IMP] Field "Active" to enable/disable synchronization for POSes. The multi-session parameter is required now to provide compatibility with "POS Multi Session Menu" module and other modules that put common settings in "POS Multi Session" (#679)

* [IMP] required multi session for POS

* [ADD] new setting 'active' to enable sync for POS

* [DEMO] update demo

* [LINT] fix lint errors

* [DOC] update module version

* [ADD] default multi session

* [DEMO] update demo data

* [DEMO] update demo

* [IMP] default multi session

* [IMP] default multi session for not demo POSes

* [DOC] update changelog

* [REF] refactoring code

* [REF] refactoring code

* [REF] refactoring code

* [FIX] help for multi_session_id

* [10.0][FIX] pos_mobile: css styles (#678)

* [FIX] css styles for pos_mobile

* [LINT] fix lint error

* :book: note about using browser's network tool

* :sparkles: Support different Credit Accounts  (#702)

(e.g. internal for employees and usual for customers)

Other updates are:

+- **ADD:** Cash out feature
+- **ADD:** Multiple debit credit accounts
+- **ADD:** Smart button with debts/credits on a customer view
+- **ADD:** Credits via discount
+- **FIX:** Debt history for Chinese localization
+- **FIX:** Error when user doesn't have timezone
+- **FIX:** user_id was always replaced to Administrator in pos.order
+- **IMP:** Updating debts/credits data for partners in opened orders after restoring the internet connection
+- **ADD:** Option 'Autopay' for debt journals

* :rainbow: methods renamings (#720)

* :ambulance: fix different errors related to Conflict Sync problem  (#709)

* :zap: restore longpoll conection by clicking the icon

Conflicts:
	pos_longpolling/doc/changelog.rst
	pos_longpolling/static/src/js/pos_longpolling.js

* :zap: added synchronization among the same POS

Conflicts:
	pos_multi_session/__manifest__.py
	pos_multi_session/doc/changelog.rst
	pos_multi_session/static/src/js/pos_multi_session.js

* :ambulance: endless sync all errors and conflicts during syncing

* :ambulance: old orders in new session

Conflicts:
	pos_multi_session/static/src/js/pos_multi_session.js

* :rainbow: further renamings

* :ambulance: added session_id in case of equal login_numbers

* :ambulance: sync_all requests

* :ambulance: fix error on order creating after connection reestablished

* :reestablishing a connection if sync all request didnt pass on the loading screen:

* :ambulance: fix order numbers after second internet diconnection

* :zap: Attribute ``unit`` to display the product UoM on order receipt (#707)

* :rainbow: improvement of reestablishing a connection on load sync_all request

* :rainbow: decreased sync_all request quantity

* :fire_engine: wrongly set model_id

random id from another table was used

* :book: index.rst usage about simultaneously opened same pos

* :rainbow: refactoring of run_ID, message_ID

* :rose: better explanation

* :rainbow: message_ID

* :heart_eyes: debug in longpoll error message

* :ambulance: minor merge fixes

* :book: pos_multi_session_sync: it's recommended to use workers=1 (#726)

* :tada::one::zero: pos_barcode_sync (#692)

* :zap: spinning longpoll icon after clicking on it

* :rainbow: refactoring of syncnotification widgets

* :zap: orange color for poll icons if poll response was not recieved

* :ambulance: fixes for poll_response_status

* :rainbow: longpolling renamings

* :book: longpoll icon meanings

* :rose: improve doc

* :zap: closing a warning message after connection is reestablished

* :tada::one::zero:pos_cashbox module (#659)

* :sos: add FIXME note

*  :ambulance::one::zero: Orderlines added to existing orders in offline mode won't be lost after restoring the connection (#731)

* [IMP] pos_multi_session: new option for POS in offline mode

* :rainbow: sync all refactoring

* :rainbow: removed sync_all func

* :rainbow: removed sync_all for pos ms r

* :rainbow: new variable instead of offline timer relation

* :ambulance: ref ms_update_order in case of empty order

* :rainbow: removed init_lock this.offline_orderline depends on ready.state

* :ambulance: issue related to offline updates

* :ambulance: lost of orders after synching

* :rainbow: assigning offline_orderline as false

* :tada: pos_orders_history, pos_orders_history_reprint, pos_orders_history_return modules (#734)

* [ADD] added new module the orders history in POS (#265)

* [ADD] added new module the orders history in POS

* [FIX] Fixes travis errors

* [DOC] added readme, index, changlog files

* [FIX] revert doc files

* [FIX] lint errors

* [FIX] lint error

* [ADD] new module

* Revert "[ADD] new module"

This reverts commit 841c6c467e01be56fe8391030b8085f0524929a6.

:q

* [FIX] sorting records

* [FIX] load order after pay

* [FIX] remove pyc files

* [FIX] updated orders in POS after save order to server

* Update __manifest__.py

* [DOC] update index.rst for coming updates where Order History is activated by default

* [FIX] remove old code

* [FIX] default value, updated READMY

* [ADD] filters in POS, new settings in pos.config

* [ADD] group name in view

* [ADD] new module 'Reprint Paid Orders'

* [ADD] filter by table

* [FIX] old code

* [10.0][NEW] pos_orders_history_reprint module; pos_order_history fixes (it-projects-llc/addons-dev#325)

* [FIX] pos orders history updates and fixes

* [10.0][DOC] pos_orders_history documentation (it-projects-llc/addons-dev#400)

* [DOC] pos_orders_history documentation

* [DOC] updates for docs

* [DOC] screenshots

* [REF] pos_orders_history: code refactoring (it-projects-llc/addons-dev#417)

* [REF] refactoring code

*  [10.0][NEW] pos_orders_history_return (it-projects-llc/addons-dev#422)

* [IMP] save mode pos_order_history

* [10.0][NEW] pos_orders_history_return

* [IMP] show all posted orders

* [REF] refactoring code for pos_orders_history

* [IMP] group name

* [DEV] check return order,fix max return product qty

* [DEV] load lines after load orders

* [DEV] check max return qty

* [IMP] save all orders history

* [IMP] show new warning message if not products for return

* [IMP] new mode 'return withour receipt'

* [FIX] change qty for units

* [IMP] barcode in receipt, [FIX] order is undefined

* [IMP] return orders is temp orders (do not sync when use pus_multi_session)

* [10.0][IMP] correct payment method for refunded orders [FIX] max return qty after orderline removing (it-projects-llc/addons-dev#438)

* [IMP] payment method for refund order

* [FIX] show max return qty after remove a product from order

*  [10.0][REF] pos_order_history_reprint: refactoring the code (it-projects-llc/addons-dev#454)

* [REF] refactoring pos_order_history_reprint

* [DOC] update doc,manifest

* [DOC] update index.rst for pos_orders_history module

* [CI] add pos_orders_hitory tests

* [CI] fix pos_orders_history test

* [FIX] qweb link in manifest

* [CI] add test for pos_orders_history_reprint

* [CI] add tests

* [FIX] css style

* [CI] fix test for pos_orders_history_return

* [10.0][REF] pos_orders_history_reprint: for compatibility with pos_receipt_custom (it-projects-llc/addons-dev#468)

* [10.0] :muscle: pos_orders_history_reprint: refactoring the code (it-projects-llc/addons-dev#471)

* [REF] remove old code

* [IMP] move reprint button to orderline

* [REF] refactoring code

* [IMP] reprint receipt for posted orders

* [IMP] show warning popup if receipt is not exist

* [FIX] remove old ticket from receipt screen

* [FIX] order is undefined

* :book: pos_orders_history: updates for documentation, instructions (it-projects-llc/addons-dev#523)

* :book: pos_orders_history: updates for documentation, instructions

* :book: additional fixes

* :book: clarify key feature

* :book: pos_orders_history: doc updates (it-projects-llc/addons-dev#529)

* :book: pos_orders_history: updates for documentation, instructions

* :book: additional fixes

* :book: clarify key feature

* :book: pos_orders_history: doc updates

* :book: pos_orders_history_reprint: documentation (it-projects-llc/addons-dev#530)

* :book: pos_orders_history_reprint: documentation

* :book: pos_orders_history_reprint: main image

* :rainbow: violation warning

* :book: index.rst - minor fix

* :book::one::zero: pos_orders_history_return description (it-projects-llc/addons-dev#534)

* :book: pos_orders_return description

* :book: pos_orders_history_return: doc updates

* :book: pos_orders_history_return - main image

* :book: pos_orders_history_return - minor fix

* :book: pos_orders_history_return: update docs

* :book: pos_orders_history_return: updates for main image

* :book: information about compatible modules

* :rainbow: pos_orders_history_return: violation warnings

* :shield: fix lint errors

* :shield: fix lint errors

* :shield: fix lint errors

* :rainbow: violation warning

* :ambulance: fixed doubling offline orderlines after connection was restored

* :ambulance: missed dependency

in pos_product_available_negative 9.0

*  :ambulance: self is undefined(#742)

* :ambulance: self is undefined

* :book: change module version

* * :zap: do not merge orderlines if the orderline has notes(#743)

* :zap: do not merge orderlines if the orderline has notes

* :book: update module version

* :zap: do not merger if a orderline has a predefined note

* :book: update version

* :book: fix update tag

* :sos::one::one: pos_debt_notebook_rewards is not ported yet

* :euro: new price

Maintenance and support cost much

* :ambulance: issue related to debt loading after creating a new partner (#729)

* :arrow_up: migration fixes

* :rainbow: @class to hasclass

* :ambulance: debt_notebook test errors

* :shield: pos_invoice_pay tests

* [10.0][NEW] POS Receipt Custom (it-projects-llc/addons-dev#445)

* [10.0][NEW] POS Receipt Custom

* [DOC] index.rst: fix formatting and spelling

* [FIX] field name

* [10.0][NEW] POS Receipt format for Order Printers (it-projects-llc/addons-dev#446)

* [10.0][NEW] POS Receipt format for Order Printers

* [IMP] receipt qweb

* [IMP] printing the 'new order' header

* [ADD] printing transfer table info

* [ADD] new setting in pos config

* [IMP] print receipt for different tables

* [DOC] Update documentation

* [FIX] add security

* [REF] refactoring code

* [IMP] pos_print_method compatibility with pos_order_receipt_custom

* [IMP] compatibility with pos_order_note module

* [CI] add test

* [DOC] Updates for index.rst

* [FIX] field strings

* [10.0][NEW] pos_receipt_custom [IMP] pos_order_receipt_custom: show cancellation reason; display product unit (it-projects-llc/addons-dev#453)

* [IMP] show discount name for pos_product_category_discount

* [10.0][NEW] pos_receipt_custom

* [FIX] error of template name during rendering qweb

* [IMP] get receipt type

* [IMP] receipt type

* [FIX] remote receipt type after printing

* [FIX] order is undefined

* [DATA] fix qweb template

* [FIX] receipt_template is undefined

* [DATA] update data

* [DATA] show cancellation reason

* [IMP] display product unit

*  [REF] pos_order_receipt_custom: refactoring for new notes format (it-projects-llc/addons-dev#464)

* [IMP] pos_restaurant_base: new arg in ComputeChange function

* [REF] refactoring pos_order_receipt_custom

* [IMP] order receipt

* [10.0][IMP] compatibility pos_receipt_custom and pos_orders_history_reprint (it-projects-llc/addons-dev#467)

* [REF] refactoring of pos_receipt_custom

* [REF] refactoring of pos_order_receipt_custom

* [IMP] compatibility pos_receipt_custom with pos_orders_history_reprint

* [10.0][FIX] pos_receipt_custom: open_time is undefined (it-projects-llc/addons-dev#469)

* [FIX] grammatical error

* [FIX] open_time is undefined

* [10.0][IMP] compatibility the custom tickets with pos_orders_history_reprint [FIX] open_time is undefined after reload page (it-projects-llc/addons-dev#472)

* [IMP] compatibility custom tickets with pos_orders_history_reprint

* [FIX] open_time is undefined after reload page

* [10.0] :ambulance: compatibility pos_receipt_custom and pos_print_method; :heart_eyes: show waters on receipt (it-projects-llc/addons-dev#474)

* [FIX] check order custom receipt

* [IMP] show waters on receipt

* :arrow_up::one::one: pos_receipt_custom

* :arrow_up::one::one: pos_order_receipt_custom

* :fire_engine: lastorderline is undefined

* :bomb: fix getting object element

* :fire_engine: printbill is undefined

* [FIX] pos_debt_notebook: Wrong merge on es.po causing module crash

* :green_heart: pos_order_receipt_custom

* [NEW] module pos_discount_absolute (it-projects-llc/addons-dev#280)

* [NEW] pos_discount_absolute module (it-projects-llc/addons-dev#370)

* [DEV] absolute_discount [CI]

* [IMP] condition based on the permanent attribute [FIX] possible bug on a floor screen

* [ADD] recalculation option

* :arrow_up::one::one: pos_discount_absolute

* :fire: error in test, discounts are disabled

* :memo: licenses for pos_discount_absolute

* :shield: pos_receipt_custom

* :shield: increased timeouts between steps

* :sos::one::one: modules are not ported yet

* :shield: extrernal tests fixes for 11v

* :handshake: New Translations! We need your help ... 

 to translate more: https://www.it-projects.info/page/translate

* :arrow_up::one::one: invalid syntax error in python3.5+

* :sos::one::one: pos_cashbox is not ported yet

* :arrow_up::one::one: pos_orders_history port

* :arrow_up::one::one: pos_orders_history_return port

* :arrow_up::one::one: pos_orders_history_reprint port

* :rose: fa icon for Return button

* :bath: No need to use "Cancel" here, because history menu doesn't require any action to cancel. We need to use "Back" instead

* [10.0][NEW] pos_disable_payment_restaurant module (it-projects-llc/addons-dev#394)

* [REF] remove old code

* [10.0][NEW] Disable payments in Restaurant

* [10.0][FIX] pos_disable_payment_restaurant: line is undefined (it-projects-llc/addons-dev#404)

* :arrow_up::one::one: pos_disable_payment_restaurant

* :ambulance: added onchange methods for disable_payments, error with line removing when decrease amount is prohibited

* :fire: display total in the currency format with *.00 when recalculation option is on

* :arrow_up::one::one: pos_debt_notebook_rewards port

* :bath: versions in README

* :bath: correct version in manifest file

* :ambulance: compatibilty pos_receipt_custom with pos_discount and pos_discount_absolute

* :doc: fix version in docs (#756)

* :bath: refactoring of the field dependencies, logic enhancement

* :fire: fixed discarded discounts after changing a client

* :ambulance: pos_disable_payments_restaurant logic improvements, pos_dispay wrong cashier errors

* :bath: compatibility with pos_cancel and small ref

* :fire: pos_order_receipt_custom compatibility with pos...reprint

* :fire: pos_receipt_custom and pos_ms compatibility error